# Run a locally built image in the foreground:
#   docker compose up --build
#
# Run it in the background and follow the logs:
#   docker compose up --build -d
#   docker compose logs -f

services:
  wrp:
    build:
      context: .
    image: mrhoeve/wrp:latest
    ports:
      - "8080:8080"
#    environment:
#      resourceurl: https://resource.example/page-containing-the-ods-link
#      callbackurl: https://consumer.example/updated
#      callbackparameter: token=xyz
#      cacheduration: 15
#      cachetimeunit: MINUTES
#      httpconnecttimeout: 10s
#      httpreadtimeout: 60s
#      httpmaxdownloadsize: 256MB
#      odsmaxuncompressedsize: 256MB
#      odsmaxrows: 100000
#      versioncheckenabled: true
#      versioncheckinitialdelay: 30s
#      versioncheckinterval: 6h

